function dayoftheweek(){

 const m2síc =  document.getElementById("month").value
 let mesíc 
switch (m2síc){ 

    
    case 1:
     mesíc =  console.log("Únor.")
    break;
    case 2:
        mesíc = console.log("Březen.")
    break;
    case 3:
        mesíc =console.log("Duben.")
    break;
    case 4:
        mesíc =console.log("Květen.")
    break;
    case 5:
        mesíc =console.log("Červen.")
    break;
    case 6:
        mesíc =console.log("Červenec.")
    break;
case 7:
    mesíc =console.log("Srpen.")
    break;
    case 8:
        mesíc =console.log("Září.")
    break;
    case 9:
    console.log("Říjen.")
    break;
    case 10:
        mesíc =console.log("Listopad.")
    break;
   case 11:
    mesíc =console.log("Leden.")
                   break;
    
  
}


}

function Numbers(){



}